name: CI

on:
  pull_request:

jobs:
  setup:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: npm-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

  static-checks:
    name: Static checks
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: npm-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Static checks
        run: npm run static-checks

  tests:
    name: Unit tests
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Load current commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Read nvmrc
        id: read-nvmrc
        run: echo "::set-output name=version::$(cat .nvmrc)"
        shell: bash

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ steps.read-nvmrc.outputs.version }}

      - name: Restore cache
        uses: actions/cache@v2
        id: npm-cache
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci
